package com.onetag.javadev;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

class ExtractorUnitTest {
    private static final List<String> extractionResult = List.of(
    "Katharine Hepburn",
    "Daniel Day-Lewis",
    "Spencer Tracy",
    "Jack Nicholson",
    "Sally Field",
    "Sean Penn",
    "Bette Davis",
    "Luise Rainer",
    "Hilary Swank",
    "Vivien Leigh",
    "Jodie Foster",
    "Fredric March",
    "Ingrid Bergman",
    "Olivia de Havilland",
    "Elizabeth Taylor",
    "Gary Cooper",
    "Frances McDormand",
    "Marlon Brando",
    "Glenda Jackson",
    "Meryl Streep",
    "Tom Hanks",
    "Dustin Hoffman",
    "Jane Fonda",
    "Marlee Matlin",
    "Janet Gaynor",
    "Jennifer Lawrence",
    "Audrey Hepburn",
    "Joan Fontaine",
    "Grace Kelly",
    "Julie Christie",
    "Jennifer Jones",
    "Gwyneth Paltrow",
    "Brie Larson",
    "Barbra Streisand",
    "Liza Minnelli",
    "Sophia Loren",
    "Charlize Theron",
    "Joanne Woodward",
    "Norma Shearer",
    "Emma Stone",
    "Julie Andrews",
    "Natalie Portman",
    "Ginger Rogers",
    "Adrien Brody",
    "Reese Witherspoon",
    "Judy Holliday",
    "Richard Dreyfuss",
    "Patricia Neal",
    "Sissy Spacek",
    "Maximilian Schell",
    "Claudette Colbert",
    "Anne Bancroft",
    "Helen Hayes",
    "James Stewart",
    "Jane Wyman",
    "Marion Cotillard",
    "Diane Keaton",
    "Nicolas Cage",
    "Kate Winslet",
    "Julia Roberts",
    "Emma Thompson",
    "Eddie Redmayne",
    "Charles Laughton",
    "Clark Gable",
    "Robert Donat",
    "Helen Hunt",
    "William Holden",
    "Loretta Young",
    "Halle Berry",
    "Nicole Kidman",
    "Maggie Smith",
    "Russell Crowe",
    "Yul Brynner",
    "Faye Dunaway",
    "William Hurt",
    "Charlton Heston",
    "Holly Hunter",
    "Sidney Poitier",
    "Rami Malek",
    "Robert De Niro",
    "Mary Pickford",
    "Jamie Foxx",
    "Philip Seymour Hoffman",
    "Greer Garson",
    "Broderick Crawford",
    "Ernest Borgnine",
    "Ray Milland",
    "Ben Kingsley",
    "José Ferrer",
    "Simone Signoret",
    "Jean Dujardin",
    "Jon Voight",
    "Joan Crawford",
    "Kevin Spacey",
    "Susan Hayward",
    "Warner Baxter",
    "Paul Muni",
    "Laurence Olivier",
    "Louise Fletcher",
    "Bing Crosby",
    "Casey Affleck",
    "Cher",
    "Leonardo DiCaprio",
    "Ellen Burstyn",
    "Jeremy Irons",
    "Rod Steiger",
    "Lee Marvin",
    "Gene Hackman",
    "Kathy Bates",
    "Alec Guinness",
    "Michael Douglas",
    "James Cagney",
    "George C. Scott",
    "Cate Blanchett",
    "Olivia Colman",
    "Matthew McConaughey",
    "Emil Jannings",
    "Cliff Robertson",
    "Forest Whitaker",
    "Geoffrey Rush",
    "Paul Scofield",
    "Sandra Bullock",
    "Jessica Lange",
    "F. Murray Abraham",
    "Roberto Benigni",
    "Wallace Beery",
    "Gregory Peck",
    "Denzel Washington",
    "Burt Lancaster",
    "Paul Lukas",
    "Anna Magnani",
    "Victor McLaglen",
    "Jack Lemmon",
    "David Niven",
    "Shirley MacLaine",
    "Susan Sarandon",
    "Colin Firth",
    "Humphrey Bogart",
    "Al Pacino",
    "Robert Duvall",
    "Lionel Barrymore",
    "Julianne Moore",
    "Anthony Hopkins",
    "Shirley Booth",
    "Art Carney",
    "Ronald Colman",
    "Rex Harrison",
    "Gary Oldman",
    "Peter Finch",
    "Jeff Bridges",
    "Geraldine Page",
    "Helen Mirren",
    "John Wayne",
    "George Arliss",
    "Paul Newman",
    "Marie Dressler",
    "Henry Fonda",
    "Jessica Tandy"
);

    @Test
    public void checkResult() {
        Extractor extractor = ExtractorFactory.getExtractor();

        Assertions.assertNotNull(extractor);

        List<String> result = extractor.extract();

        Assertions.assertNotNull(result);
        Assertions.assertEquals(extractionResult.size(), result.size());

        for (int i = 0; i < extractionResult.size(); ++i) {
            if (i < 8 || i > 10) {
                Assertions.assertEquals(extractionResult.get(i), result.get(i));
            } else {
                Assertions.assertTrue(extractionResult.get(i).equals(result.get(8))
                        || extractionResult.get(i).equals(result.get(9))
                        || extractionResult.get(i).equals(result.get(10)));
            }
        }
    }
}